/**
 * Central mapping from chat activity (tool calls, reasoning) to a color
 * category, and from that category to the theme CSS variable that tints the
 * activity row's icon and title.
 *
 * The variables themselves (`--tools-activity-*`) are generated by the theme
 * CSS variable generator from existing theme tokens, so every light/dark
 * theme gets sensible accents with no hard-coded palette. Themes can override
 * each category via `colors.tools.activity` in their JSON.
 *
 * The `system` category is intentionally neutral: it resolves to no variable,
 * so those rows keep the regular muted tool styling.
 */

export type ActivityColorCategory =
  | 'thinking'
  | 'read'
  | 'edit'
  | 'write'
  | 'shell'
  | 'search'
  | 'web'
  | 'question'
  | 'agent'
  | 'system';

/** Reasoning and justification rows are both the model's thinking. */
export const REASONING_ACTIVITY_CATEGORY: ActivityColorCategory = 'thinking';

const ACTIVITY_COLOR_VAR_PREFIX = '--tools-activity-';

const ACTIVITY_TOOL_CATEGORIES = {
  // Read & codebase exploration
  read: 'read',
  view: 'read',
  file_read: 'read',
  cat: 'read',
  list: 'read',
  ls: 'read',
  dir: 'read',
  list_files: 'read',
  lsp: 'read',

  // File edits
  edit: 'edit',
  multiedit: 'edit',
  edit_file: 'edit',
  apply_patch: 'edit',
  str_replace: 'edit',
  str_replace_based_edit_tool: 'edit',

  // File creation
  write: 'write',
  write_file: 'write',
  create: 'write',
  file_write: 'write',

  // Shell commands
  bash: 'shell',
  shell: 'shell',
  cmd: 'shell',
  terminal: 'shell',

  // File search
  grep: 'search',
  find: 'search',
  search: 'search',
  ripgrep: 'search',
  glob: 'search',

  // Web research
  webfetch: 'web',
  fetch: 'web',
  curl: 'web',
  wget: 'web',
  websearch: 'web',
  'web-search': 'web',
  search_web: 'web',
  codesearch: 'web',
  google: 'web',
  bing: 'web',
  duckduckgo: 'web',
  perplexity: 'web',

  // Questions to the user
  question: 'question',

  // Agents
  task: 'agent',
  skill: 'agent',

  // Neutral system bookkeeping: keeps the regular muted tool styling.
  todowrite: 'system',
  todoread: 'system',
  plan_enter: 'system',
  plan_exit: 'system',
  structuredoutput: 'system',
  structured_output: 'system',
  openchamber: 'system',
  openchamber_web: 'system',
  openchamber_memory: 'system',
} satisfies Record<string, ActivityColorCategory>;

/**
 * A tool name as it arrives on a message part: usually a string, occasionally
 * absent on defensive renderers. Parsing happens here, at the boundary.
 */
export type ActivityToolName = string | undefined | null;

/** Strips MCP prefixes and `:N` suffixes, matching the chat tool renderers. */
export function normalizeActivityToolName(toolName: ActivityToolName): string {
  if (toolName === undefined || toolName === null) return '';
  const trimmed = toolName.trim().toLowerCase();
  if (!trimmed) return '';

  const withoutIndex = trimmed.replace(/:\d+$/, '');
  if (withoutIndex.includes('.')) {
    const parts = withoutIndex.split('.').filter(Boolean);
    return parts[parts.length - 1] ?? withoutIndex;
  }
  return withoutIndex;
}

export function getActivityColorCategory(toolName: ActivityToolName): ActivityColorCategory {
  return ACTIVITY_TOOL_CATEGORIES[normalizeActivityToolName(toolName)] ?? 'system';
}

export interface ActivityColorStyle {
  icon?: string;
  title?: string;
}

/** The CSS color value for a category, or null when the category is neutral. */
export function getActivityColorVar(category: ActivityColorCategory | undefined): string | null {
  if (!category || category === 'system') return null;
  return `var(${ACTIVITY_COLOR_VAR_PREFIX}${category})`;
}

/**
 * Icon/title colors for an activity category, or null when the row should
 * keep its regular neutral tool styling.
 */
export function getActivityColorStyle(
  category: ActivityColorCategory | undefined,
): ActivityColorStyle | null {
  const color = getActivityColorVar(category);
  if (!color) return null;
  return { icon: color, title: color };
}
