// Git library public entrypoint
// Re-exports all Git operations, credentials, and identity storage functions

export * from './service.js';
export * from './credentials.js';
export * from './identity-storage.js';
export * from './execution-errors.js';
export * from './execution-coordinator.js';
export * from './context-resolver.js';

export {
  createGitExecutionService,
  gitExecutionService,
  isGitRepository,
  getStatus,
  getGlobalIdentity,
  getRemoteUrl,
  getCurrentIdentity,
  hasLocalIdentity,
  getDiff,
  listUntrackedPaths,
  getUntrackedDiffs,
  getRangeDiff,
  getBranchBase,
  getRangeFiles,
  getFileDiff,
  listStashes,
  countStashFiles,
  stashPush,
  stashApply,
  stashDrop,
  stashPop,
  getBranches,
  getWorktrees,
  validateWorktreeCreate,
  previewWorktreeCreate,
  createWorktree,
  getWorktreeBootstrapStatus,
  removeWorktree,
  getLog,
  getCommitFiles,
  getCommitFileDiff,
  getRemotes,
  removeRemote,
  isLinkedWorktree,
  validateWorktreeDirectory,
  canonicalizeWorktreeState,
  getConflictDetails,
  getIntegrateConflictDetails,
  getRepositoryRoot,
  revertFile,
  stageFile,
  stageFiles,
  unstageFile,
  unstageFiles,
  applyHunk,
  checkoutCommit,
  cherryPick,
  revertCommit,
  resetToCommit,
  checkoutBranch,
  createBranch,
  deleteBranch,
  renameBranch,
  deleteRemoteBranch,
  setLocalIdentity,
  commit,
  push,
  pull,
  fetch,
  rebase,
  abortRebase,
  continueRebase,
  merge,
  abortMerge,
  continueMerge,
  computeIntegratePlan,
  abortIntegrate,
  continueIntegrate,
  integrateWorktreeCommits,
  resolvePrimaryWorktreeRoot,
  resolveWorktreeTopLevel,
  getCommitSummaries,
  isCherryPickInProgress,
  collectDiffs,
  ensureWorktreeLongpaths,
  populateWorktreeWithLockRecovery,
} from './execution-service.js';
