/**
 * i18n runtime — locale detection and resolution.
 *
 * This module provides locale detection across Web, Desktop (Tauri), and VS Code
 * runtimes. It does NOT import React or Zustand — it's pure utility logic.
 *
 * Paraglide's `setLocale` / `getLocale` come from generated `@/paraglide/runtime.js`
 * so that all locale state flows through a single source of truth.
 */

// Re-export Paraglide runtime functions.
// @ts-expect-error generated by Paraglide at build time
import { setLocale as paraglideSetLocale, getLocale } from '@/paraglide/runtime.js';
import { isVSCodeRuntime } from '@/lib/desktop';

export type Locale = 'en' | 'zh-CN' | 'zh-TW' | 'vi' | 'ja';

export const AVAILABLE_LOCALES: readonly Locale[] = ['en', 'zh-CN', 'zh-TW', 'vi', 'ja'] as const;

export const LOCALE_LABELS: Record<Locale, string> = {
  en: 'English',
  'zh-CN': '简体中文',
  'zh-TW': '繁體中文',
  vi: 'Tiếng Việt',
  ja: '日本語',
};

/** Re-export Paraglide's getLocale — returns the current active locale. */
export { getLocale };

/**
 * Set the active locale. Updates Paraglide's internal state so that
 * all subsequent `import { m } from '@/lib/i18n/messages'` calls
 * return strings in the new locale.
 *
 * Paraglide's setLocale is synchronous and does not trigger re-renders
 * by itself. The `useI18nStore` handles the React update.
 */
export function setLocale(locale: Locale): void {
  paraglideSetLocale(locale);
}

/**
 * Detect the initial locale for this session.
 *
 * Priority:
 * 1. Persisted preference (from useUIStore localStorage)
 * 2. VS Code runtime language (if in VS Code)
 * 3. Browser/OS language (navigator.language)
 * 4. Fallback: 'en'
 */
export function detectInitialLocale(persistedLocale?: string): Locale {
  // 1. Persisted preference wins
  if (persistedLocale && isSupportedLocale(persistedLocale)) {
    return persistedLocale;
  }

  if (typeof window === 'undefined') return 'en';

  // 2. VS Code: locale passed via runtime APIs
  if (isVSCodeRuntime()) {
    const vscodeLang = getVSCodeLanguage();
    if (vscodeLang) return normalizeLocale(vscodeLang);
  }

  // 3. Desktop & Web: navigator.language mirrors the OS locale
  // Desktop (Tauri) webview inherits navigator.language from the OS automatically
  return normalizeLocale(navigator.language || 'en');
}

/**
 * Normalize browser/runtime locale strings to our supported Locale IDs.
 *
 * Examples:
 *   'zh-CN' → 'zh-CN'
 *   'zh_CN' → 'zh-CN'
 *   'zh-Hans-CN' → 'zh-CN'
 *   'zh-TW' → 'zh-TW'
 *   'zh-HK' → 'zh-TW'
 *   'zh-Hant' → 'zh-TW'
 *   'en-US' → 'en'
 *   'en-GB' → 'en'
 *   'vi-VN' → 'vi'
 *   'ja-JP' → 'ja'
 */
export function normalizeLocale(raw: string): Locale {
  const lower = raw.toLowerCase().replace(/_/g, '-');

  // Chinese: map Simplified Chinese variants to zh-CN
  if (lower === 'zh-cn' || lower === 'zh-hans' || lower.startsWith('zh-hans-')) return 'zh-CN';
  // Chinese: map Traditional Chinese variants to zh-TW
  if (lower === 'zh-tw' || lower === 'zh-hk' || lower === 'zh-mo' || lower === 'zh-hant' || lower.startsWith('zh-hant-')) return 'zh-TW';

  if (lower.startsWith('vi')) return 'vi';
  if (lower.startsWith('ja')) return 'ja';
  if (lower.startsWith('en')) return 'en';

  // Unsupported language → fallback to English
  return 'en';
}

// --- Internal helpers ---

function isSupportedLocale(locale: string): locale is Locale {
  return (AVAILABLE_LOCALES as readonly string[]).includes(locale);
}

/**
 * Get VS Code's configured language from the runtime APIs.
 * VS Code passes its UI language via `vscode.env.language` through
 * the runtime APIs bridge.
 */
function getVSCodeLanguage(): string | undefined {
  const apis = (window as unknown as { __OPENCHAMBER_RUNTIME_APIS__?: { runtime?: { language?: string } } }).__OPENCHAMBER_RUNTIME_APIS__;
  return apis?.runtime?.language;
}
