#Requires -Version 5.1
<#
.SYNOPSIS
    Guardian smoke test (Windows-only).

.DESCRIPTION
    End-to-end runtime check for the OpenChamber guardian on Windows.
    Mirrors `scripts/guardian-smoke-test.sh` 1:1 with PowerShell idioms.

    Steps:
      1. Spawn `node packages/web/bin/openchamber-guardian.js --data-dir <tmp>`.
      2. Poll the discovery file (`<data-dir>/managed-opencode-handoff-v2/port`)
         for `127.0.0.1:<port>` (up to 10s).
    3. Run the cross-platform authenticated smoke client. It rejects
       unauthenticated and replayed IPC, launches a real managed child fixture,
       checks health and owner metadata, stops the child, and verifies list.
    4. Send authenticated `{ method: "shutdown" }` and wait for the process
       to exit (up to 5s). Assert the discovery file is removed.

    Exit codes:
      0 = ok (or skipped on non-Windows / when node.exe is unavailable)
      1 = smoke test failure

.PARAMETER DataDir
    Optional override for the temp data dir.

.PARAMETER PortPath
    Optional override for the discovery file path. Forwarded to the
    entrypoint via `--port-path`.
#>

[CmdletBinding()]
param(
    [string]$DataDir,
    [string]$PortPath
)

$ErrorActionPreference = 'Stop'
$ProgressPreference = 'SilentlyContinue'

# Skip cleanly on non-Windows. Same pattern as the bash version: exit 0
# so the workflow does not need a separate platform gate.
if (-not $IsWindows -and -not ($env:OS -like '*Windows*')) {
    Write-Host 'skip: not Windows'
    exit 0
}

function Fail([string]$msg) {
    # Use the raw stderr writer rather than `Write-Error`. With
    # `$ErrorActionPreference = 'Stop'` (set at the top of the
    # script) `Write-Error` raises a terminating error *before*
    # `exit 1` runs and floods the log with a stack trace that
    # is just noise. Writing to the stderr stream directly and
    # then `exit 1` keeps the failure message terse.
    [Console]::Error.WriteLine("fail: $msg")
    # On any failure, dump the spawned entrypoint's stdout and
    # stderr to the script's own stdout (via `Write-Host`, not
    # `Write-Error`) so the next CI run surfaces the actual
    # runtime output in `gh run view --log-failed`. Without this,
    # the redirected log files live in the runner's ephemeral
    # temp dir and are not visible to the reviewer.
    if ($LogFile -and (Test-Path -LiteralPath $LogFile)) {
        Write-Host "---- $LogFile ----"
        Get-Content -LiteralPath $LogFile -Raw | Write-Host
    }
    if ($LogErrFile -and (Test-Path -LiteralPath $LogErrFile)) {
        Write-Host "---- $LogErrFile ----"
        Get-Content -LiteralPath $LogErrFile -Raw | Write-Host
    }
    exit 1
}

$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$RepoRoot = (Resolve-Path (Join-Path $ScriptDir '..')).Path
$GuardianEntry = Join-Path $RepoRoot 'packages/web/bin/openchamber-guardian.js'

if (-not (Test-Path -PathType Leaf $GuardianEntry)) {
    Fail "guardian entry not found at $GuardianEntry"
}

# The guardian uses better-sqlite3, which is a Node native module and is not
# supported by Bun. The workflow rebuilds the hoisted package with npm before
# this script runs, so use the same Node runtime for the guardian and smoke
# client. This also keeps local execution aligned with the CI ABI.
if (-not (Get-Command node.exe -ErrorAction SilentlyContinue)) {
    Write-Host 'skip: node.exe not available'
    exit 0
}

# Build the temp data dir + log file.
# Track whether the operator passed an explicit -DataDir. We only
# delete the directory on cleanup when we generated it ourselves;
# never recurse `-Force` over a user-supplied path.
if (-not $DataDir) {
    $DataDirAutoGenerated = $true
    # Keep guardian state under the per-user local application root. The
    # checked-out workspace can inherit BUILTIN\Users write access, which is
    # intentionally rejected by the guardian's strict ancestor ACL policy.
    $dataBase = if ($env:LOCALAPPDATA) { $env:LOCALAPPDATA } else { [System.IO.Path]::GetTempPath() }
    $tempLeaf = [System.Guid]::NewGuid().ToString('N')
    $DataDir = Join-Path $dataBase "openchamber-guardian-smoke-$tempLeaf"
} else {
    $DataDirAutoGenerated = $false
    $tempLeaf = [System.Guid]::NewGuid().ToString('N')
}
New-Item -ItemType Directory -Path $DataDir -Force | Out-Null
$logBase = [System.IO.Path]::GetFullPath((Join-Path $ScriptDir '.smoke-logs'))
$LogRoot = Join-Path $logBase "openchamber-guardian-smoke-$tempLeaf"
$RunDir = Join-Path $LogRoot 'run'
New-Item -ItemType Directory -Path $RunDir -Force | Out-Null
$LogFile = Join-Path $RunDir 'guardian.log'
$LogErrFile = Join-Path $RunDir 'guardian.err.log'

# The Windows startup branch in `bin/openchamber-guardian.js` defaults
# `--port-path` to `<data-dir>/managed-opencode-handoff-v2/port`. Mirror
# that here so the polling step does not need a second helper.
if ($PortPath) {
    $ResolvedPortPath = $PortPath
} else {
    $ResolvedPortPath = Join-Path (Join-Path $DataDir 'managed-opencode-handoff-v2') 'port'
}

$proc = $null
$cleanup = {
    if ($null -ne $proc -and -not $proc.HasExited) {
        try { Stop-Process -Id $proc.Id -Force -ErrorAction SilentlyContinue } catch { }
    }
    if ($DataDirAutoGenerated) {
        try {
            if (Test-Path -PathType Container $DataDir) {
                Remove-Item -LiteralPath $DataDir -Recurse -Force -ErrorAction SilentlyContinue
            }
        } catch { }
    }
}

try {
    $arguments = @($GuardianEntry, '--data-dir', $DataDir)
    if ($PortPath) {
        $arguments += @('--port-path', $ResolvedPortPath)
    }

    $proc = Start-Process -FilePath 'node.exe' `
        -ArgumentList $arguments `
        -RedirectStandardOutput $LogFile `
        -RedirectStandardError $LogErrFile `
        -PassThru -WindowStyle Hidden

    # Poll for the discovery file. 30s budget, 0.2s intervals.
    # The first Windows run may be slow because `icacls`
    # and Node's startup overhead dominate; 10s proved too tight
    # on cold runners.
    $portFile = $ResolvedPortPath
    $found = $false
    for ($i = 0; $i -lt 150; $i += 1) {
        if (Test-Path -PathType Leaf $portFile) { $found = $true; break }
        Start-Sleep -Milliseconds 200
    }
    if (-not $found) {
        Fail "guardian port file not created at $portFile (see $LogFile and $LogErrFile)"
    }

    # Parse `127.0.0.1:<port>` from the discovery file.
    $body = (Get-Content -LiteralPath $portFile -Raw -Encoding UTF8).Trim()
    if ($body -notmatch '^127\.0\.0\.1:(\d+)$') {
        Fail "port file contents not in expected host:port form: $body"
    }
    $port = [int]$Matches[1]

$secretPath = Join-Path (Join-Path $DataDir 'managed-opencode-handoff-v2') 'guardian-auth.secret'
$pidMarker = Join-Path (Join-Path $DataDir 'managed-opencode-handoff-v2') 'guardian.pid'
    if (-not (Test-Path -LiteralPath $secretPath -PathType Leaf)) {
        Fail "guardian auth secret not created at $secretPath"
    }
    $smokeClient = Join-Path $RepoRoot 'scripts/guardian-smoke-client.js'
    $smokeFixture = Join-Path $RepoRoot 'scripts/guardian-test-opencode.js'
    if (-not (Test-Path -LiteralPath $smokeClient -PathType Leaf)) {
        Fail "guardian smoke client not found at $smokeClient"
    }
    if (-not (Test-Path -LiteralPath $smokeFixture -PathType Leaf)) {
        Fail "guardian smoke fixture not found at $smokeFixture"
    }

    # The cross-platform client performs the authenticated `list`, `spawn`,
    # `health`, `stop`, and `shutdown` requests over the real Windows TCP
    # transport. It deliberately runs under Node so the fixture uses the same
    # runtime/native-module ABI as the guardian on windows-latest.
    & node.exe $smokeClient `
        '--port-path' $ResolvedPortPath `
        '--secret-path' $secretPath `
        '--fixture' $smokeFixture `
        '--cwd' $RepoRoot
    if ($LASTEXITCODE -ne 0) {
        Fail "guardian authenticated managed-child smoke client failed with exit code $LASTEXITCODE"
    }

    # Wait up to 5s for the guardian to actually exit.
    $exited = $false
    for ($i = 0; $i -lt 50; $i += 1) {
        if ($proc.HasExited) { $exited = $true; break }
        Start-Sleep -Milliseconds 100
    }
    if (-not $exited) {
        Fail 'guardian did not exit after shutdown'
    }

    # The discovery file should have been removed on guardian exit.
    if (Test-Path -PathType Leaf $portFile) {
        Fail "port file still present at $portFile after guardian exit"
    }
    if (Test-Path -PathType Leaf $pidMarker) {
        Fail "guardian PID marker still present at $pidMarker after guardian exit"
    }

    Write-Host 'ok'
    exit 0
}
finally {
    & $cleanup
}
