#Requires -Version 5.1
<#
.SYNOPSIS
    Guardian smoke test (Windows-only).

.DESCRIPTION
    End-to-end runtime check for the OpenChamber guardian on Windows.
    Mirrors `scripts/guardian-smoke-test.sh` 1:1 with PowerShell idioms.

    Steps:
      1. Spawn `node packages/web/bin/openchamber-guardian.js --data-dir <tmp>`.
      2. Poll the discovery file (`<data-dir>/managed-opencode-handoff-v2/port`)
         for `127.0.0.1:<port>` (up to 10s).
      3. Send `{ method: "list" }` over TCP via .NET `TcpClient`; assert the
         response is an array.
      4. Send `{ method: "shutdown" }` and wait for the process to exit
         (up to 5s). Assert the discovery file is removed.

    Exit codes:
      0 = ok (or skipped on non-Windows / when node.exe is unavailable)
      1 = smoke test failure

.PARAMETER DataDir
    Optional override for the temp data dir.

.PARAMETER PortPath
    Optional override for the discovery file path. Forwarded to the
    entrypoint via `--port-path`.
#>

[CmdletBinding()]
param(
    [string]$DataDir,
    [string]$PortPath
)

$ErrorActionPreference = 'Stop'
$ProgressPreference = 'SilentlyContinue'

# Skip cleanly on non-Windows. Same pattern as the bash version: exit 0
# so the workflow does not need a separate platform gate.
if (-not $IsWindows -and -not ($env:OS -like '*Windows*')) {
    Write-Host 'skip: not Windows'
    exit 0
}

function Fail([string]$msg) {
    # Use the raw stderr writer rather than `Write-Error`. With
    # `$ErrorActionPreference = 'Stop'` (set at the top of the
    # script) `Write-Error` raises a terminating error *before*
    # `exit 1` runs and floods the log with a stack trace that
    # is just noise. Writing to the stderr stream directly and
    # then `exit 1` keeps the failure message terse.
    [Console]::Error.WriteLine("fail: $msg")
    exit 1
}

$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$RepoRoot = (Resolve-Path (Join-Path $ScriptDir '..')).Path
$GuardianEntry = Join-Path $RepoRoot 'packages/web/bin/openchamber-guardian.js'

if (-not (Test-Path -PathType Leaf $GuardianEntry)) {
    Fail "guardian entry not found at $GuardianEntry"
}

if (-not (Get-Command node.exe -ErrorAction SilentlyContinue)) {
    Write-Host 'skip: node.exe not available'
    exit 0
}

# Build the temp data dir + log file.
# Track whether the operator passed an explicit -DataDir. We only
# delete the directory on cleanup when we generated it ourselves;
# never recurse `-Force` over a user-supplied path.
if (-not $DataDir) {
    $DataDirAutoGenerated = $true
    $tempBase = [System.IO.Path]::GetTempPath()
    $tempLeaf = [System.Guid]::NewGuid().ToString('N')
    $DataDir = Join-Path $tempBase "openchamber-guardian-smoke-$tempLeaf"
} else {
    $DataDirAutoGenerated = $false
}
New-Item -ItemType Directory -Path $DataDir -Force | Out-Null
$RunDir = Join-Path $DataDir 'run'
New-Item -ItemType Directory -Path $RunDir -Force | Out-Null
$LogFile = Join-Path $RunDir 'guardian.log'

# The Windows startup branch in `bin/openchamber-guardian.js` defaults
# `--port-path` to `<data-dir>/managed-opencode-handoff-v2/port`. Mirror
# that here so the polling step does not need a second helper.
if ($PortPath) {
    $ResolvedPortPath = $PortPath
} else {
    $ResolvedPortPath = Join-Path (Join-Path $DataDir 'managed-opencode-handoff-v2') 'port'
}

$proc = $null
$cleanup = {
    if ($null -ne $proc -and -not $proc.HasExited) {
        try { Stop-Process -Id $proc.Id -Force -ErrorAction SilentlyContinue } catch { }
    }
    if ($DataDirAutoGenerated) {
        try {
            if (Test-Path -PathType Container $DataDir) {
                Remove-Item -LiteralPath $DataDir -Recurse -Force -ErrorAction SilentlyContinue
            }
        } catch { }
    }
}

try {
    $arguments = @($GuardianEntry, '--data-dir', $DataDir)
    if ($PortPath) {
        $arguments += @('--port-path', $ResolvedPortPath)
    }

    $proc = Start-Process -FilePath 'node.exe' `
        -ArgumentList $arguments `
        -RedirectStandardOutput $LogFile `
        -RedirectStandardError $LogFile `
        -PassThru -WindowStyle Hidden

    # Poll for the discovery file. 10s budget, 0.2s intervals.
    $portFile = $ResolvedPortPath
    $found = $false
    for ($i = 0; $i -lt 50; $i += 1) {
        if (Test-Path -PathType Leaf $portFile) { $found = $true; break }
        Start-Sleep -Milliseconds 200
    }
    if (-not $found) {
        Fail "guardian port file not created at $portFile (see $LogFile)"
    }

    # Parse `127.0.0.1:<port>` from the discovery file.
    $body = (Get-Content -LiteralPath $portFile -Raw -Encoding UTF8).Trim()
    if ($body -notmatch '^127\.0\.0\.1:(\d+)$') {
        Fail "port file contents not in expected host:port form: $body"
    }
    $port = [int]$Matches[1]

    # Open a TCP connection and send a `list` request. BCL built-in
    # `TcpClient` only — no PowerShell-specific module needed.
    $client = [System.Net.Sockets.TcpClient]::new()
    # Mirror the bash version's `setTimeout` budget for the
    # JSON-line round-trip. The bash script uses 5s for `list`
    # and 3s for `shutdown`; BCL `TcpClient` only exposes a
    # single per-socket value, so 5s is the safe upper bound.
    $client.ReceiveTimeout = 5000
    $client.SendTimeout = 5000
    try {
        $client.Connect('127.0.0.1', $port)
    } catch {
        Fail "could not connect to guardian at 127.0.0.1:$port ($($_.Exception.Message))"
    }
    $stream = $client.GetStream()
    $writer = [System.IO.StreamWriter]::new($stream, [System.Text.Encoding]::UTF8)
    $reader = [System.IO.StreamReader]::new($stream, [System.Text.Encoding]::UTF8)
    $writer.NewLine = "`n"
    try {
        $listId = '1'
        $listReq = "{`"id`":`"$listId`",`"method`":`"list`",`"params`":{}}" + "`n"
        $writer.WriteLine($listReq)
        $writer.Flush()
        $listLine = $reader.ReadLine()
        if ($null -eq $listLine) {
            Fail 'no list response received (connection closed)'
        }
        $listObj = $listLine.Trim() | ConvertFrom-Json -ErrorAction Stop
        if ($null -eq $listObj.result) {
            Fail "list response missing 'result' field: $($listLine.Trim())"
        }
        if ($listObj.result -isnot [System.Array]) {
            Fail "list response result is not an array: $($listLine.Trim())"
        }

        # Send `shutdown`. The guardian may close the socket before our
        # ReadLine returns, so tolerate EOF here. Per the W-A shutdown
        # ordering fix, the entrypoint removes the discovery file
        # before exiting.
        $shutdownReq = "{`"id`":`"2`",`"method`":`"shutdown`",`"params`":{}}" + "`n"
        $writer.WriteLine($shutdownReq)
        $writer.Flush()
        try { $null = $reader.ReadLine() } catch [System.IO.IOException] { }
    }
    finally {
        try { $writer.Dispose() } catch { }
        try { $reader.Dispose() } catch { }
        try { $stream.Dispose() } catch { }
        try { $client.Close() } catch { }
    }

    # Wait up to 5s for the guardian to actually exit.
    $exited = $false
    for ($i = 0; $i -lt 50; $i += 1) {
        if ($proc.HasExited) { $exited = $true; break }
        Start-Sleep -Milliseconds 100
    }
    if (-not $exited) {
        Fail 'guardian did not exit after shutdown'
    }

    # The discovery file should have been removed on guardian exit.
    if (Test-Path -PathType Leaf $portFile) {
        Fail "port file still present at $portFile after guardian exit"
    }

    Write-Host 'ok'
    exit 0
}
finally {
    & $cleanup
}
